### ISSUE TITLE
tirdad fails to build on Linux >= 5.7.0

### ISSUE THREAD

**Issue by 0xC0ncord** [0xsirus/tirdad#11]
It seems that as of [this upstream commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0bd476e6c67190b5eb7b6e105c8db8ff61103281), `kallsyms_lookup_name` is no longer exported and thus tirdad cannot use it. The result is that tirdad cannot build against kernel 5.8 or higher.

The resulting error is:
```
ERROR: modpost: "kallsyms_lookup_name" [/var/tmp/portage/sys-kernel/tirdad-0.1.16/work/tirdad-0.1.16-1/module/tirdad.ko] undefined!
```

**Comment by 0xC0ncord** [comment]
I have also encountered this on Linux 5.7.19, so it might apply to >= 5.7.0 as well.

**Comment by 0xsirus** [comment]
Thanks for reporting the issue. Unfortunately there doesn't seem to be a clean equivalent to use when this function is not exported anymore. I probably need to resort back to use hacky ways if I want it to compile successfully on newest kernels.

**Comment by 0xC0ncord** [comment]
If it helps, [LKRG](https://github.com/openwall/lkrg) uses a hacky way to resolve the symbol at runtime that may be worth looking into.

**Comment by 0xsirus** [comment]
I implemented the kprobe idea and gave it a test and it seems to work fine and it's easier than other ways that I had in mind. However to make sure everything works as expected I need to test it more and in different kernels which might take some time given my current schedule. Thanks again for your collaboration.
