### ISSUE TITLE
Linux kernel 6.1.7-1 compatibility broken?

### ISSUE THREAD

**Issue by adrelanos** [0xsirus/tirdad#14]
It's been reported that tirdad might be incompatible with Linux kernel 6.1.7-1
https://github.com/QubesOS/qubes-issues/issues/8037#issuecomment-1430586718

Is tirdad still supported?

Does it work for you?

**Comment by 0xsirus** [comment]
I currently don't have a 6.1.7 image to try but I tested it on kernel 6.2-rc8 and worked fine. Should work on 6.1.7 too.
