### ISSUE TITLE
tirdad and linux-libre kernel

### ISSUE THREAD

**Issue by Tech4951** [0xsirus/tirdad#15]
Thanks for your work!
Great benefits of tirdad make no sense if the kernel itself may have backdoors: https://www.fsfla.org/ikiwiki/selibre/linux-libre/index.en.html
How can tirdad be used with the installed linux-libre kernel? When installed, tirdad is still requiring the vanilla kernel headers...
The GNU kernel is Freesh Libre Debian kernel (LTS) from here: https://www.fsfla.org/ikiwiki/selibre/linux-libre/freesh.en.html

Thanks.

**Comment by 0xsirus** [comment]
If you prefer not to use the default headers you should place the required headers (there are a lot of them) in the directory of the module and change the inclusion lines at the top of the source before compiling. By the way why don't you use the default Linux headers? They are just C definitions for OS structures and constants which are used in all kernel modules.
