### ISSUE TITLE
Please implement as kernel patch - hooks dont work w/ CFI

### ISSUE THREAD

**Issue by sempervictus** [0xsirus/tirdad#20]
I love function hooking as much as the next guy, but on my targets, not my systems. kCFI is now public, as is the CET version, and Android (at least GrapheneOS) has used LLVM's old CFI for a while (plus RAP has been around for a decade for folks who prefer fine-grained protection for calls _and_ returns).

Implementing this functionality as a patch to the linux source tree would allow CFI coverage for the code, and extend its lifetime past the point where use of CFI becomes the norm, not just "the security person's way of building stuff" (plus, security-oriented people are the likely users of this code).

**Comment by 0xsirus** [comment]
There's already a similar open issue: https://github.com/0xsirus/tirdad/issues/19
Please refer to that.
