### ISSUE TITLE
is it possible to compile it for 4.10 kernel 

### ISSUE THREAD

**Issue by nav60** [0xsirus/tirdad#21]
Hi,
Thanks for sharing your work. I am trying to use it for 4.10 kernel and it is giving siphash.h error. siphash is not available for this kernel version. however your work required 4.14 version.

**Comment by 0xsirus** [comment]
Hello,

4.14 or newer kernels are recommended for using tirdad. I had written the initial versions of the code without siphash but after Linux started to use it in the core net functions I adapted my code to use it as well to follow standard kernel coding practices. Kernel 4.10 is not supported any more.

**Comment by nav60** [comment]
Hello,
I am facing issue while compiling it on kernel 4.14.  it is giving error on 295-298  ```
#define HANDLER(t,l,ret,...) t l ## h_hk(struct kprobe * kp, struct pt_regs * r\
					__VA_OPT__(,) __VA_ARGS__){\
						ret;\
					}
```
After searching it, i found that it is due to std=c99 standard because gcc uses the gnu standard. I have changed it in the kernel Makefile from gnu to c99 standard but it is not working.  gcc version is 4.8.6.
it is working on latest kernel and distributions. Please guide
