### ISSUE TITLE
compilation of tirdad on 4.14 and gcc 4.8.6

### ISSUE THREAD

**Issue by nav60** [0xsirus/tirdad#22]
Hello,
I am facing issue while compiling it on kernel 4.14.  it is giving error on 295-298  ```
#define HANDLER(t,l,ret,...) t l ## h_hk(struct kprobe * kp, struct pt_regs * r\
					__VA_OPT__(,) __VA_ARGS__){\
						ret;\
					}
```
After searching it, i found that it is due to std=c99 standard because gcc uses the gnu standard. I have changed it in the kernel Makefile from gnu to c99 standard but it is not working.  gcc version is 4.8.6.
it is working on latest kernel and distributions. Please guide

**Comment by 0xsirus** [comment]
Hello,

The current kernel release is 6.7. I don't remember what the oldest version was that I tested the module on. Is there any reason that you are using these old versions?

**Comment by 0xsirus** [comment]
Hello,

The current stable kernel release is 6.7.x. I don't remember what the oldest version was that I tested the module on. Is there any reason that you are using these old versions?

**Comment by 0xsirus** [comment]
Hello,

The current stable kernel release is 6.7.x. I don't remember what the oldest version was that I tested the module on. Is there any reason that you are using these old versions?

**Comment by 0xsirus** [comment]
Hello,

The current stable kernel release is 6.7.x. I don't remember what the oldest version was that I tested the module on. Is there any reason that you are using these old versions?

**Comment by nav60** [comment]
Yes sir. Its embedded device and unable to update the kernel on it. ChatGPT suggested to check gcc support for c99 . when i change the c99 in the kernel build system, it gives a lot of errors. It seems conflict of compiler and kernel build system.

**Comment by nav60** [comment]
I am not good in c so it will not be easy for me. However, I have tried to use your patches (got it from github issues) and set the tcp_random_isn to 1. As per my understanding, after setting tcp_random_isn it will produce random TCP sequences and make difficult for port scanners tools to detect the OS version based on TCP port test cases. 
It is my understanding of your work because port scanner also uses the same logic to guess the OS behavior against TCP ports.

**Comment by 0xsirus** [comment]
To fix the compile error in the older gcc, change

```
#define HANDLER(t,l,ret,...) t l ## h_hk(struct kprobe * kp, struct pt_regs * r\
					__VA_OPT__(,) __VA_ARGS__){\
						ret;\
					}

HANDLER(int,pre,return 0)
HANDLER(void,post,return,unsigned long flags)
```

to:

```
int preh_hk(struct kprobe * kp, struct pt_regs * r){return 0;}
void posth_hk(struct kprobe * kp, struct pt_regs * r,unsigned long flags){return;}
```

then compile.

**Comment by nav60** [comment]
Hi, Thanks for help. Let me check and get back to you

**Comment by nav60** [comment]
Hi,
Thank you for solving compilation issue and finally module compiled successfully. However, i cannot achieve my desirable results. 

Thanks again for prompt responses.
