### ISSUE TITLE
tirdad statically in kernel kernel

### ISSUE THREAD

**Issue by adrelanos** [0xsirus/tirdad#6]
Is it possible / sane to compile tirdad statically in the kernel? I.e. not load it as a module.

**Comment by 0xsirus** [comment]
This is what I had initially done. But it requires the whole kernel be recompiled and you said that you prefer not to use a custom kernel.
However it you mean to add it to the ELF binary of the kernel, yes in theory it's possible but I don't recommend to go that way. It's too hacky and hard to analyze and maintain.

**Comment by adrelanos** [comment]
> But it requires the whole kernel be recompiled and you said that you prefer not to use a custom kernel.

Indeed. This was the correct decision at that time. I am not suggesting do major rework. If you are wondering, this question came up in this context:

* https://forums.whonix.org/t/tcp-isn-cpu-information-leak-protection-tirdad/8552/8
* https://forums.whonix.org/t/kernel-hardening/7296/357

We might build our own kernel one day. But there is still a lot work ahead related to packaging and integration. 

* https://github.com/Whonix/hardened-kernel
* https://forums.whonix.org/t/kernel-recompilation-for-better-hardening/7598

Far ahead. If compiling tirdad one day as a module would be as simple as changing from `m` to `y` and wouldn't make maintenance on your side harder, then we might go for it. But it's a small thing. Probably we'll never get to a point where we can completely statically compile a kernel and disable module load support for reasons unrelated to tirdad.
